### ISSUE TITLE
Existential crisis?

### ISSUE THREAD

**Issue by banacorn** [bloodyowl/reason-react-update#3]
[I](https://github.com/reasonml/reason-react/issues/408
)'ve had a good time using this package. But then I stumbled upon this [tweet](https://twitter.com/vanwal_j/status/1102011599039139840):

Someone mentioned about reducers à la ReasonReact:
> useReducer is awesome but I just feel like we miss a way to easily trigger side effects and re-dispatch actions within reducers à la ReasonReact :)

Dan Abramov then replied:
> There are unclear questions about how that would work in concurrent mode.

I'm wondering if that's the case 🤔

**Comment by bloodyowl** [comment]
AFAIK it should work. the main question was about commit cancellation, but as we **create** a new ref in order to store side-effects (https://github.com/bloodyowl/reason-react-update/blob/5dc1ac815b93afa9037d8455da6b883f89c162dd/src/ReactUpdate.re#L29), React should be able to go back to its previous state without trouble.

we'll reopen this issue if we start to see bugs when concurrent mode becomes the default in React.
